apiVersion: apps/v1
kind: Deployment
metadata:
  name: iels-station-manager
spec:
  selector:
    matchLabels:
      app: iels-station-manager
  template:
    metadata:
      labels:
        app: iels-station-manager
        service: ielsapi
    spec:
      containers:
      - name: iels-station-manager
        image: codewithnayakdockerhub/stationmanager:1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80
          
